### PR TITLE
Port benchmarks to criterion

### PR DESCRIPTION
**Pull request by vks**
This uses more solid statistics and works on stable.
A new benchmark with random bits has been added.

### CODE REVIEW

**Comment by bluss** [comment]
Cool. I don't think a port to criterion is worthwhile. Look at that swarm of deps it brings in (see travis).

**Comment by vks** [comment]
Yes, but they are dev-dependencies. Anyway, it was useful for #18.

**Comment by vks** [comment]
Criterion requires Rust 1.23, while fixedbitset works with 1.12. But the old benchmarks shouldn't work on any stable, so I'm a bit confused.

**Comment by bluss** [comment]
The maintainer has to make the decisions, that's what we are for. Adding 59 crates as dev-dependencies is a no-go, optional or not.

**Comment by bluss** [comment]
Thanks anyway. I'll just close this. I have had hopes that criterion would replace "[bencher](https://docs.rs/bencher/)" but I wouldn't use it in this state. A lot of the crate looks awesome, of course.

**Pull request closed without merging**
