### PR TITLE
Add copy_bit functionality

### PR DESCRIPTION
**Pull request by fuine**
This PR adds simple copy_bit functionality. It's use case is tracking boolean values for `EdgeIndices` in `petgraph`'s `Graph`, while removing some edges - last edge is put into the place of the removed edge, and so boolean variable for the last edge should be copied according to it's new index.

I'm not sure if this is the most optimal implementation, so i'd love some comments on it.

### CODE REVIEW

**Comment by bluss** [comment]
Interesting function. I understand the need, having a variable just to handle the borrowing in the right order is a bit sad.

The issue is simply that methods have their arguments in the wrong order! :D 
such a function works too:

```rust
fn set_bit(index: usize, value: bool, set: &mut FixedBitSet) {
    set.set(index, value)
}
```

Call using `set_bit(to, fb[from], &mut fb);`

**Comment by bluss** [comment]
Just musing, we'll merge this as it is. Good choice of method name.

**Comment by fuine** [comment]
Doesn't your solution introduce a small overhead (call to `Vec`'s `get` followed by match on the `Option` as opposed to `get_unchecked` with if on `bool`)? I think that it's hard to tell without explicitly benching both solutions, I will implement them and compare results once i get some free time.

**Comment by bluss** [comment]
Both solutions are bounds checking, I don't think it's a difference. My gut feeling is that it's no difference.

**Comment by fuine** [comment]
I've just measured both implementations and it looks like there's no significant difference between the two. I'm not sure if you want that PR merged or should we leave API as it is?

**Comment by bluss** [comment]
I assumed you wanted to add this for ergonomics (due to the method + argument evaluation order / borrowck annoyance)

**Comment by fuine** [comment]
IMO this PR introduces nice interface for this operation and i would like it to be merged, I just wasn't sure what was your take on the matter :)

**Comment by bluss** [comment]
Don't have time to make releases now

**Comment by bluss** [comment]
Sorry, I forgot about this. Now 0.1.2 is released. I did tweak your function (see master branch).

**Pull request merged**
